services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_URL=sqlite:////app/data/database.db
      - DB_ASYNC_URL=sqlite+aiosqlite:////app/data/database.db
    volumes:
      - ./data:/app/data



