"""delete auth

Revision ID: 329af1793778
Revises: 7a4bb7ad373b
Create Date: 2026-06-02 14:37:57.989695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329af1793778'
down_revision: Union[str, Sequence[str], None] = '7a4bb7ad373b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_token')
    # op.create_unique_constraint(None, 'user', ['username'])
    with op.batch_alter_table("user") as batch_op:
        batch_op.create_unique_constraint(
            "uq_user_username",
            ["username"]
        )
    op.drop_column('user', 'password')
    with op.batch_alter_table("user") as batch_op:
        batch_op.drop_column("email")
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=5), nullable=False))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=256), nullable=False))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=256), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_table('access_token',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
